### ISSUE TITLE
GEN-XSS clober requests

### ISSUE THREAD

**Issue by heathj** [nccgroup/tracy#85]
If a payload created from GEN-XSS is used in multiple requests, they end up clobbering each other. Should make separate tracers rows for each request. This might involve UI changes so that events get mapped to hosts and payload rather than just payload.

**Comment by jacobheath** [comment]
Fixed in 02d8f0e5923774693fcb12240b5faef0999335c1

**Comment by mrobertsNCC** [comment]
I think this is still a problem. While it accepts multi request now. I did not update the logic in proxy to handle it.

**Comment by jacobheath** [comment]
I'm going to change it in the plugin version.

**Comment by heathj** [comment]
Closed by 7c7413dec0d2465758d3883e6c704592c5ac06bc
